FROM python:3.10.7
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY DemandDataLoader.py .
COPY weather_config.py .
COPY WeatherDataLoader.py .
COPY DataLoader.py .
COPY DataSplitter.py .
COPY DemandDataFrameBuilder.py .
COPY DemandModel.py .
COPY CloudStorage.py .
COPY update_data.py .
COPY config.py .

CMD ["python", "update_data.py"]